# Describes the format for available Kurrali Irrigation services

manual_irrigation:
  name: Manual Irrigation
  description: Turn on immediately for a set period.
  fields:
    entity_id:
      description: Name of the entity.
      example: "binary_sensor.station_1"
      required: true
      selector:
        entity:
          integration: kurrali_irrigation
          domain: binary_sensor


    time:
      description: The amount of time to run.
      example: "00:10"
      required: true
      selector:
        time:

stop_irrigation:
  name: Stop Irrigation
  description: Turn off current irrigation
