default_config:

logger:
  default: info
  logs:
    custom_components.kurrali_irrigation: debug

kurrali_irrigation:
  controllers:
    all_zones_config:
      show:
        timeline: true
    zones:
      - name: Lawn Back Deck
      - name: Lawn River Deck
      - name: Lawn River Chooks
      - name: Lawn Shed House
      - name: Lawn Front House
      - name: Lawn Front Tree Line
      - name: Lawn
      - name: Lawn
      - name: Lawn
      - name: Lawn Washing Line
      - name: Lawn
      - name: Veggie Garden
      - name: Orchard
      - name: Gym Garden
      - name: Deck and Driveway
      - name: Baskets and Herbs
    sequences:
      - name: "Program A"
        schedules:
          - time: "10:00"
        zones:
          - zone_id: 1
            duration: "01:00"
          - zone_id: 2
            duration: "01:00"
          - zone_id: 3
            duration: "01:00"
          - zone_id: 12
            duration: "00:16"
          - zone_id: 13
            duration: "01:00"
      - name: "Program B"
        schedules:
          - time: "10:00"
        zones:
          - zone_id: 4
            duration: "01:00"
          - zone_id: 5
            duration: "01:00"
          - zone_id: 6
            duration: "01:00"
          - zone_id: 12
            duration: "00:16"
          - zone_id: 14
            duration: "01:00"
      - name: "Program C"
        schedules:
          - time: "10:00"
        zones:
          - zone_id: 7
            duration: "01:00"
          - zone_id: 8
            duration: "01:00"
          - zone_id: 9
            duration: "01:00"
          - zone_id: 12
            duration: "00:16"
          - zone_id: 14
            duration: "01:00"
      - name: "Program D"
        schedules:
          - time: "10:00"
        zones:
          - zone_id: 10
            duration: "01:00"
          - zone_id: 11
            duration: "01:00"
          - zone_id: 12
            duration: "00:16"
          - zone_id: 15
            duration: "01:00"
          - zone_id: 16
            duration: "01:00"
  history:
    enabled: true
